### ISSUE TITLE
Feature request: return modified files.

### ISSUE THREAD

**Issue by scvsoft-javierrotelli** [pheel/path-watcher-action#4]
Hi! I'd love to have modified files as a value for further processing. 

#1 has my implementation of this.

**Comment by pheel** [comment]
Good idea. Merged!

**Comment by scvsoft-javierrotelli** [comment]
👋  I don't want to be annoying, but when do you think this can be in a release?

Thanks!

**Comment by pheel** [comment]
https://github.com/pheel/path-watcher-action/releases/tag/v2

**Comment by scvsoft-javierrotelli** [comment]
Thanks!!!
